# NumPy (Numerical Python)
Librería Open Source que se usa en casi todos los campos de la ciencia e ingeniería.

Estandar universal para trabajar con datos numéricos y está en el core de los campos científicos y de datos en Python.

NumPy se utiliza de forma extensa en Pandas, SciPy, Matplotlib, scikit-learn, scikit-image y otras librerías científicas.

## ndarray
La librería NumPy contiene arreglos multidimensionales y estructuras de datos de matriz.

 - Tabla de elementos del mismo tipo
 - Este arreglo puede tener varias dimensiones o ejes
 

In [1]:
import numpy as np

a = np.array([2,3,4])
a

array([2, 3, 4])

### ndarray.ndim
Número de dimensiones del arreglo.

### ndarray.shape
Las dimensiones del arreglo.

### ndarray.size
Número total de elementos.

### ndarray.dtype
Describe el tipo de datos de los elementos del arreglo. NumPy también provee sus propios tipos. numpy.int32, numpy.int16, y numpy.float64 por ejemplo.

### ndarray.itemsize
El tamaño en bytes de cada elemento del arreglo.

### ndarray.data
El buffer con los elementos del arreglo.


In [2]:
# Crear arreglos
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [3]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [9]:
ceros = np.zeros((3, 4))
ceros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
unos = np.ones( (2,3,4))
unos

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [40]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [14]:
np.arange( 0, 2, 0.3 )

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [15]:
np.linspace( 0, 2, 9 )

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [21]:
import math
x = np.linspace( 0, 2*math.pi, 100 )
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [24]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


# Operaciones básicas
 - Operadores aritméticos aplican Hadamard (Por elemento), regresan un nuevo arreglo

In [43]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [44]:
c = a-b
c

array([20, 29, 38, 47])

In [27]:
b**2

array([0, 1, 4, 9])

In [28]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [29]:
a<35

array([ True,  True, False, False])

In [31]:
# Producto matriz
A = np.array( [[1,1],
               [0,1]] )
B = np.array( [[2,0],
               [3,4]] )
print(A * B)                       # elementwise product
print(A @ B)                       # matrix product
print(A.dot(B))                    # another matrix product

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [34]:
# Métodos
rg = np.random.default_rng(1)  # create instance of default random number generator
a = rg.random((2,3))
print(a)
print(a.sum())
print(a.min())
print(a.max())

[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]
3.290252281866131
0.14415961271963373
0.9504636963259353


Muchos otros [métodos](https://numpy.org/doc/stable/user/quickstart.html#functions-and-methods-overview)

# Cambiar la forma

In [35]:
a = np.floor(10*rg.random((3,4)))
print(a)
print(a.shape)

[[8. 4. 5. 0.]
 [7. 5. 3. 7.]
 [3. 4. 1. 4.]]
(3, 4)


In [37]:
a.ravel()

array([8., 4., 5., 0., 7., 5., 3., 7., 3., 4., 1., 4.])

In [38]:
a.reshape(6,2)

array([[8., 4.],
       [5., 0.],
       [7., 5.],
       [3., 7.],
       [3., 4.],
       [1., 4.]])

In [39]:
a.T

array([[8., 7., 3.],
       [4., 5., 4.],
       [5., 3., 1.],
       [0., 7., 4.]])

# Referencias
[Referencia de NumPy](https://numpy.org/doc/stable/reference/index.html)
[NumPy para MATLAB Users](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html)